// Real-world inspired tactical presets for 7v7 football simulation
export const DEFAULT_TACTICAL_STYLE = 'BALANCED';

export const TACTICAL_STYLES = {
    BALANCED: {
        id: 'BALANCED',
        name: 'Balanced',
        shortName: 'Balanced',
        description: 'Structured 2-3-1 shape. Maintains width, depth, and support without extreme risk.',
        attackPush: 8,
        defensiveLine: 18,
        compactness: 0.45,
        verticalFollow: 0.35,
        widthScale: 1.0,
        roleDepthAttack: { DEFENDER: -14, MIDFIELDER: 2, FORWARD: 14 },
        roleDepthDefend: { DEFENDER: -10, MIDFIELDER: -4, FORWARD: 6 },
        maxChasers: 2,
        chaserRoles: ['MIDFIELDER', 'FORWARD'],
        pressDistance: 16,
        pressRoles: ['FORWARD'],
        passProbabilityMod: 1.0,
        passWidthBonus: 1.0,
        passCentralBonus: 1.0,
        passVerticalBonus: 1.0,
        passStrengthMod: 1.0,
        supportBlendMod: 1.0,
        shootAggression: 1.0,
        dribbleBias: 1.0
    },
    POSSESSION: {
        id: 'POSSESSION',
        name: 'Possession',
        shortName: 'Tiki-Taka',
        description: 'Pep Guardiola / Spain style. Short passes, triangles, patient circulation, and compact support.',
        attackPush: 5,
        defensiveLine: 22,
        compactness: 0.55,
        verticalFollow: 0.5,
        widthScale: 0.95,
        roleDepthAttack: { DEFENDER: -10, MIDFIELDER: 0, FORWARD: 10 },
        roleDepthDefend: { DEFENDER: -8, MIDFIELDER: -2, FORWARD: 4 },
        maxChasers: 2,
        chaserRoles: ['MIDFIELDER', 'FORWARD'],
        pressDistance: 14,
        pressRoles: ['FORWARD', 'MIDFIELDER'],
        passProbabilityMod: 2.2,
        passWidthBonus: 0.6,
        passCentralBonus: 1.8,
        passVerticalBonus: 0.7,
        passStrengthMod: 0.85,
        supportBlendMod: 1.8,
        shootAggression: 0.7,
        dribbleBias: 0.6
    },
    COUNTER_ATTACK: {
        id: 'COUNTER_ATTACK',
        name: 'Counter Attack',
        shortName: 'Counter',
        description: 'Mourinho / Simeone transitions. Sit deep, protect space, then explode vertically on turnover.',
        attackPush: 14,
        defensiveLine: 12,
        compactness: 0.7,
        verticalFollow: 0.25,
        widthScale: 0.9,
        roleDepthAttack: { DEFENDER: -18, MIDFIELDER: 4, FORWARD: 20 },
        roleDepthDefend: { DEFENDER: -6, MIDFIELDER: -8, FORWARD: 12 },
        maxChasers: 1,
        chaserRoles: ['FORWARD'],
        pressDistance: 10,
        pressRoles: ['FORWARD'],
        passProbabilityMod: 1.1,
        passWidthBonus: 0.5,
        passCentralBonus: 0.8,
        passVerticalBonus: 2.5,
        passStrengthMod: 1.35,
        supportBlendMod: 0.5,
        shootAggression: 1.3,
        dribbleBias: 1.4
    },
    HIGH_PRESS: {
        id: 'HIGH_PRESS',
        name: 'High Press',
        shortName: 'Gegenpress',
        description: 'Klopp / Rangnick style. Win the ball high, swarm the carrier, and compress the pitch aggressively.',
        attackPush: 10,
        defensiveLine: 28,
        compactness: 0.65,
        verticalFollow: 0.55,
        widthScale: 1.05,
        roleDepthAttack: { DEFENDER: -8, MIDFIELDER: 6, FORWARD: 16 },
        roleDepthDefend: { DEFENDER: -4, MIDFIELDER: 2, FORWARD: 10 },
        maxChasers: 4,
        chaserRoles: ['FORWARD', 'MIDFIELDER', 'MIDFIELDER', 'DEFENDER'],
        pressDistance: 30,
        pressRoles: ['FORWARD', 'MIDFIELDER'],
        passProbabilityMod: 1.3,
        passWidthBonus: 1.0,
        passCentralBonus: 1.2,
        passVerticalBonus: 1.4,
        passStrengthMod: 1.1,
        supportBlendMod: 1.2,
        shootAggression: 1.1,
        dribbleBias: 0.9
    },
    LOW_BLOCK: {
        id: 'LOW_BLOCK',
        name: 'Low Block',
        shortName: 'Low Block',
        description: 'Catenaccio / park-the-bus. Two banks of four mentality, narrow, deep, and hard to break down.',
        attackPush: 4,
        defensiveLine: 10,
        compactness: 0.85,
        verticalFollow: 0.2,
        widthScale: 0.75,
        roleDepthAttack: { DEFENDER: -16, MIDFIELDER: -6, FORWARD: 4 },
        roleDepthDefend: { DEFENDER: -4, MIDFIELDER: -10, FORWARD: 0 },
        maxChasers: 1,
        chaserRoles: ['MIDFIELDER'],
        pressDistance: 8,
        pressRoles: [],
        passProbabilityMod: 0.7,
        passWidthBonus: 0.4,
        passCentralBonus: 1.0,
        passVerticalBonus: 0.5,
        passStrengthMod: 1.2,
        supportBlendMod: 0.4,
        shootAggression: 0.6,
        dribbleBias: 0.5
    },
    WING_PLAY: {
        id: 'WING_PLAY',
        name: 'Wing Play',
        shortName: 'Wing Play',
        description: 'Traditional wide football. Stretch play to the flanks, cross-field switches, and isolate wingers.',
        attackPush: 9,
        defensiveLine: 17,
        compactness: 0.4,
        verticalFollow: 0.3,
        widthScale: 1.45,
        roleDepthAttack: { DEFENDER: -14, MIDFIELDER: 0, FORWARD: 16 },
        roleDepthDefend: { DEFENDER: -10, MIDFIELDER: -5, FORWARD: 8 },
        maxChasers: 2,
        chaserRoles: ['MIDFIELDER', 'FORWARD'],
        pressDistance: 18,
        pressRoles: ['FORWARD'],
        passProbabilityMod: 1.4,
        passWidthBonus: 2.8,
        passCentralBonus: 0.4,
        passVerticalBonus: 0.9,
        passStrengthMod: 1.15,
        supportBlendMod: 0.8,
        shootAggression: 0.9,
        dribbleBias: 1.1
    },
    DIRECT: {
        id: 'DIRECT',
        name: 'Direct',
        shortName: 'Long Ball',
        description: 'Route-one football. Bypass midfield, hit channels early, and get the ball forward quickly.',
        attackPush: 12,
        defensiveLine: 14,
        compactness: 0.5,
        verticalFollow: 0.2,
        widthScale: 0.85,
        roleDepthAttack: { DEFENDER: -18, MIDFIELDER: -2, FORWARD: 18 },
        roleDepthDefend: { DEFENDER: -8, MIDFIELDER: -6, FORWARD: 10 },
        maxChasers: 2,
        chaserRoles: ['FORWARD', 'MIDFIELDER'],
        pressDistance: 12,
        pressRoles: ['FORWARD'],
        passProbabilityMod: 0.9,
        passWidthBonus: 0.7,
        passCentralBonus: 0.6,
        passVerticalBonus: 3.0,
        passStrengthMod: 1.5,
        supportBlendMod: 0.35,
        shootAggression: 1.2,
        dribbleBias: 1.5
    },
    TOTAL_FOOTBALL: {
        id: 'TOTAL_FOOTBALL',
        name: 'Total Football',
        shortName: 'Total',
        description: 'Cruyff / Ajax fluidity. Interchange positions, high mobility, collective pressing, and vertical combinations.',
        attackPush: 11,
        defensiveLine: 24,
        compactness: 0.5,
        verticalFollow: 0.65,
        widthScale: 1.15,
        roleDepthAttack: { DEFENDER: -6, MIDFIELDER: 8, FORWARD: 12 },
        roleDepthDefend: { DEFENDER: -6, MIDFIELDER: 0, FORWARD: 8 },
        maxChasers: 3,
        chaserRoles: ['FORWARD', 'MIDFIELDER', 'MIDFIELDER'],
        pressDistance: 24,
        pressRoles: ['FORWARD', 'MIDFIELDER', 'DEFENDER'],
        passProbabilityMod: 1.6,
        passWidthBonus: 1.2,
        passCentralBonus: 1.3,
        passVerticalBonus: 1.5,
        passStrengthMod: 1.0,
        supportBlendMod: 1.5,
        shootAggression: 1.0,
        dribbleBias: 0.8
    }
};

// Return a tactical preset by id with a safe fallback
export function getTacticalStyle(styleId) {
    return TACTICAL_STYLES[styleId] || TACTICAL_STYLES[DEFAULT_TACTICAL_STYLE];
}

// Ordered list used by the tactics UI panels
export const TACTICAL_STYLE_ORDER = [
    'BALANCED',
    'POSSESSION',
    'COUNTER_ATTACK',
    'HIGH_PRESS',
    'LOW_BLOCK',
    'WING_PLAY',
    'DIRECT',
    'TOTAL_FOOTBALL'
];
